pipeline {

    agent any
    stages { 
        stage('Initiate') {
            steps {
                echo "Testing..."
            }
        }

        stage('Build') {
            steps {
                echo "Building"
            }
        }

        stage('Deploy') {
            steps {
                echo "Deployed"
            }
        }
    }
}