pipeline {
    agent any
    stages { 
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
            post {
                success{
                    echo 'Now archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        stage ('Deploy to Staging'){
            steps {
                build job: 'deploy-staging'
            }
        }
        stage('Deploy to Production'){
            steps {
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve this buid to prod'
                }
                build job: 'deploy-prod'
            }
            post {
                success {
                    echo 'Code depoloyed to prod'
                }
                failure {
                    echo 'Deployment Failed'
                }
            }
        }
    }
}